---

- name: check for existing satellite install
  shell: hammer ping
  register: hammer_output
  changed_when: false
  failed_when: false
  check_mode: false
  ignore_errors: true

- name: run the satellite installer
  shell: "satellite-installer --scenario satellite {{ satellite_installer_options }}"
  register: satellite_installer_output
  when:
    - "'Failed to open TCP connection' in hammer_output.stderr"
